[k8s-worker-1]
distinguished_name = k8s-worker-1_distinguished_name
prompt = no
req_extensions = k8s-worker-1_req_extensions

[k8s-worker-1_req_extensions]
basicConstraints = CA:FALSE
extendedKeyUsage = clientAuth, serverAuth
keyUsage = critical, digitalSignature, keyEncipherment
nsCertType = client
nsComment = "k8s-worker-1 Certificate"
subjectAltName = DNS:k8s-worker-1, IP:127.0.0.1
subjectKeyIdentifier = hash

[k8s-worker-1_distinguished_name]
CN = system:node:k8s-worker-1
O = system:nodes
C = US
ST = Illinois
L = Chicago
